### ISSUE TITLE
Ender Chest - ender_png/s use outdated image

### ISSUE THREAD

**Issue by RoosterGold** [Poudingue/Vanilla-Normals-Renewed#10]
Ender Chest Image changed in 1.14
https://minecraft.gamepedia.com/Ender_Chest#History

The ender_n.png & ender_s.png use the old 1.13v

I assume the chest models have changed as well so inserting the old ender.png wouldn't help.

**Comment by RoosterGold** [comment]
Also for 1.15x The chest texture layout has been changed.
https://minecraft.gamepedia.com/Chest#History
End included I think.
Ender chest also has clipping issues using your pack probably due to these changes.
I haven't tested 1.14x

**Comment by Poudingue** [comment]
I’ll change the texture itself.
For the layout, I’ll change that when I switch to the new 1.15 format

**Comment by Poudingue** [comment]
Fixed in the last 1.14 version, and in the new 1.16 version
