### ISSUE TITLE
Dispenser/Dropper Naming issues

### ISSUE THREAD

**Issue by RoosterGold** [Poudingue/Vanilla-Normals-Renewed#13]
Dispenser/Dropper Fronts are named dispenser/dropper_front_horizontal_n

I checked both 1.14/1.15 minecraft.jar files, and the names are.
dropper_front
dropper_front_vertical
dispenser_front
dispenser_front_vertical

The horizontal line is no longer valid

I thought these looked off at 1st glance
Could find no rename mention in wiki history so unsure how far back this goes.

**Comment by Poudingue** [comment]
Pretty sure this is because I did not rename everything correctly with the last texture format change.
I’ll change that, thanks for warning me !

**Comment by Poudingue** [comment]
That’s fixed, I just forgot to close the issue 😄
