### ISSUE TITLE
Missing png's that are part of sets

### ISSUE THREAD

**Issue by RoosterGold** [Poudingue/Vanilla-Normals-Renewed#15]
brewing_stand_base_n
brewing_stand_base_s

cauldron_bottom_n

furnace_front_on_n
furnace_top_s

glass_s
glass_pane_top_s

quartz_block_bottom_n

I might add your quarts is the best.

entity/bed yellow_s

**Comment by Poudingue** [comment]
Thank you, I’ll handle this sooner or later :)

**Comment by Poudingue** [comment]
This is fixed, and will be included in the next update !
