### ISSUE TITLE
Hello, may I reprint your work to www.mcbbs.net？

### ISSUE THREAD

**Issue by hlnbnbnbnb** [Poudingue/Vanilla-Normals-Renewed#16]
Hello, may I reprint your work to www.mcbbs.net, the largest minecraft forum in China? My English is not good. This is machine translation
I will not create a share link again, but provide the address here
This will let more Chinese players know your material
你好，请问我可以把你的作品转载到www.mcbbs.net，中国最大的minecraft论坛吗？我的英文不好，这是机器翻译
我不会再次创建分享链接，而是提供这里的地址
这会让更多中国玩家知道您的材质

**Comment by Poudingue** [comment]
Copyright on the page : "You can do whatever you want with my texture pack, screenshots, videos, modifications for personal use or redistribution, as long as you don't sell it and provide a link to this page or my Patreon page."

So yes, just put a link to github or Patreon :)
