### ISSUE TITLE
Pack Won't Show Up

### ISSUE THREAD

**Issue by Wills767** [Poudingue/Vanilla-Normals-Renewed#17]
I have dragged the zip file into the resource pack folder many times and it won't appear in Minecraft. I have extracted it, rearranged it, downloaded it in different arrangements and it still wont show up. :/ Plz help.

**Comment by shalestorm** [comment]
You have to unzip the file for Java to read it, unlike mods with forge which stay zipped. Just take out the raw Folder within the zip and put it in your resourcePack folder

**Comment by supsm** [comment]
If it still doesn't work, try extracting the contents, then zipping the files directly, like `Vanilla-Normals-Renewed.zip\assets...` instead of `Vanilla-Normals-Renewed.zip\Vanilla-Normals-Renewed\assets...`. I had this issue too, and this fixed it.

**Comment by Poudingue** [comment]
Or you can download the latest release version here : https://github.com/Poudingue/Vanilla-Normals-Renewed/releases
