### ISSUE TITLE
DoubleChest use outdated image

### ISSUE THREAD

**Issue by 4o4E** [Poudingue/Vanilla-Normals-Renewed#19]
old:
normal_double_s.png
trapped_double_s.png
new:
normal_left_s.png
normal_right_s.png
trapped_left_s.png
trapped_right_s.png
![normal_left_s](https://user-images.githubusercontent.com/58851040/89115821-5352d180-d4bf-11ea-8fc2-8c11cac90358.png)
![normal_right_s](https://user-images.githubusercontent.com/58851040/89115822-564dc200-d4bf-11ea-8d7a-a8a642775d2f.png)
![trapped_right_s](https://user-images.githubusercontent.com/58851040/89115823-5a79df80-d4bf-11ea-9a6a-63bb4e896e5d.png)
![trapped_left_s](https://user-images.githubusercontent.com/58851040/89115824-5b127600-d4bf-11ea-9992-05185968ee8f.png)

**Comment by 4o4E** [comment]
other image
command_block_conditional_s.png
command_block_front_s.png
command_block_side_s.png
![command_block_front_s](https://user-images.githubusercontent.com/58851040/89116250-5ef4c700-d4c4-11ea-925b-eda34be2418f.png)
![command_block_side_s](https://user-images.githubusercontent.com/58851040/89116251-6025f400-d4c4-11ea-8c8e-6dec6e978eb0.png)
![command_block_conditional_s](https://user-images.githubusercontent.com/58851040/89116252-60be8a80-d4c4-11ea-8a3d-cfcc637f3c2b.png)

**Comment by Poudingue** [comment]
Chest textures should be fixed now

**Comment by Poudingue** [comment]
Brand new command block textures, no more problems :)
