### ISSUE TITLE
Parallax in the Nether issue

### ISSUE THREAD

**Issue by Repoio** [Poudingue/Vanilla-Normals-Renewed#2]
I have this problem with the parallax in the nether when combining Seus V11 with the Vanilla Normals Renewed, it only happens to me with this texture pack and this shader I have everything well configured in the Seus. I am using version 1.14.3.
I don't know why it happens :(
Sorry my english xD

![2019-07-29_14 01 52](https://user-images.githubusercontent.com/53444310/62068383-47796300-b20c-11e9-9ad4-18988e315b03.png)

As an example:
With the Robobo1221 shaders the resource pack works well and the Seus v11 works well with other resource packs with parallax.
It is confusing xD

**Comment by Poudingue** [comment]
Indeed, that's strange… Did you set up the texture resolution to x16 ?

**Comment by Poudingue** [comment]
Sooo, in the absence of response, I'll suppose it's not the case an this is not an issue related to the resource pack, so, issue close !

**Comment by limbosounds** [comment]
@Poudingue I'm not the author of issue, but... Yes, this kind of artifacts are caused by texture resolution mismatch. As soon as I set up texture resolution to 16, it's gone, thank you :)
