### ISSUE TITLE
V0.9.9.9 breaks natural block effect for glass blocks and glass pane.

### ISSUE THREAD

**Issue by ZZZXXX0110** [Poudingue/Vanilla-Normals-Renewed#20]
With V0.9.9.9 version the natural block effect with SEUS PTGI for glass block and glass pane doesn't work anymore, glass frame between glass blocks remain visible even when the natural block option is turned on.

**Comment by Poudingue** [comment]
I removed the glass textures from the pack it should fix it.
However, I kept the tinted glass, to be able to increase the intensities of the colours, because to me it’s more important than having connected tinted glass. :)
