### ISSUE TITLE
Configuration info missing

### ISSUE THREAD

**Issue by l0drex** [Poudingue/Vanilla-Normals-Renewed#22]
I'm using the SEUS Shader with Optifine and just discovered that I have to enable _Parallax Occlusion Mapping_ and set the _resolution to 16_ manually in the shader options to make use of the normal maps.
Maybe you could add this to the installation info, especially since the resolution has to be either guessed or looked up in the resource pack files.

**Comment by Poudingue** [comment]
Yeah you’re right, adding that right away 👍
