### ISSUE TITLE
Not able to see honeyblocks with seus PTGI

### ISSUE THREAD

**Issue by IvorAmlug** [Poudingue/Vanilla-Normals-Renewed#23]
Well i cant see Honey blocks they get renderet as water when i use this pack together with seus ptgi

**Comment by misaalanshori** [comment]
For me it happens even without this resourcepack, just with the default resource pack. so it might be a SEUS PTGI problem

**Comment by Poudingue** [comment]
Yeah, it’s just a PTGI problem, closing the issue.
(Transparent/translucent blocks often behave weirdly with shaders and need to be handled by the shader artists)
