### ISSUE TITLE
VNR/SEUS PTGI HRR Test 2 Grass Texture Issue.

### ISSUE THREAD

**Issue by Tenseiren** [Poudingue/Vanilla-Normals-Renewed#25]
The sides of grass seem to be rendering incorrectly in SEUS PTGI HRR 2/2.1. They do render correctly in HRR test 1.
 
 
HRR Test 2: ![2021-01-18_22 23 39](https://user-images.githubusercontent.com/77653944/104984094-19797700-59dc-11eb-8f35-8e615dd9104d.png)

HRR Test 1: 
![2021-01-18_22 24 44](https://user-images.githubusercontent.com/77653944/104984233-55144100-59dc-11eb-85e3-98fe653ed59c.png)

**Comment by Tenseiren** [comment]
*The issue seems to be caused by HRR 2's support for POM

**Comment by Poudingue** [comment]
@Horizon531 yes, disable smooth PoM it should make it better.
