### ISSUE TITLE
Honeyblocks seem to be weird 

### ISSUE THREAD

**Issue by IvorAmlug** [Poudingue/Vanilla-Normals-Renewed#29]
So whenever i load up this texture pack with seus ptgi HRR test the honey combs look like this:
![2021-02-27_16 12 35](https://user-images.githubusercontent.com/38656481/109391318-bd790b00-7916-11eb-8a0f-e535346e5cde.png)
When i use the same version but with the block config of the PATRIX texture pack it work
![2021-02-27_16 12 44](https://user-images.githubusercontent.com/38656481/109391336-cff34480-7916-11eb-8b45-1544582cda03.png)
I would use that version but the ores than look like this:
![2021-02-27_16 12 53](https://user-images.githubusercontent.com/38656481/109391341-d681bc00-7916-11eb-8390-5f995fe7efdc.png)
there supposed to look like tihs with the patrix texture pack cause it adds crystals to diamon, emerald and redstone ores.
Is there a way to fix this?

**Comment by Poudingue** [comment]
Yeah this is mostly a problem on PTGI side. I’m pretty sure this is something that will be fixed in the future.
You can take the patrix block config, and just add honey block from it to PTGI block config.
