### ISSUE TITLE
Seams between some blocks when Shader Parallax enabled

### ISSUE THREAD

**Issue by valentyn-l** [Poudingue/Vanilla-Normals-Renewed#30]
Hello! 

I wanted to report that some blocks such as **Netherrack** exhibit visible seams in the Nether when parallax is enabled.

Similarly, **Ladders** and minecart **Rails** show artifacts around the edges of the block. 

Here are some pics illustrating the issues.

![2021-03-06_12 57 58](https://user-images.githubusercontent.com/60371520/110206062-e9970d80-7e7b-11eb-8a92-4ac937ff38fe.png)

![2021-03-06_12 58 58](https://user-images.githubusercontent.com/60371520/110206070-f451a280-7e7b-11eb-9a38-1661bbe3e59d.png)

![2021-03-06_12 57 44](https://user-images.githubusercontent.com/60371520/110206050-de43e200-7e7b-11eb-873a-63a8ec3103dd.png)

**Comment by Poudingue** [comment]
Disabling "natural textures" and "alternate textures" in optifine options can alleviate the problem for blocks like cobblestone or netherrack.

But for objects with PoM, I can’t do much. I could provide an alternative "No pom" option for the individual objects with these problems. This is something that could be handled by shader artists, but it’s a very specific artifact, and it requires them to "mark" blocks to handle differently.

Lowering Pom intensity can also hide the problem a bit. (Or simply disabling it)
