### ISSUE TITLE
Textures looking "bumpy" with PTGI HRR but not with E12

### ISSUE THREAD

**Issue by LukasMFR** [Poudingue/Vanilla-Normals-Renewed#32]
Hi,
So I use 1.0.2 of your pack but weirdly the texture looks bumpy with HRR 2.1,
I am using 1.16.5 with latest version of OptiFine, I have another pack as well which brings a dark UI to Minecraft but I don't think that is the issue.

Screenshot :
![2021-04-30_11 18 12](https://user-images.githubusercontent.com/41242166/116675383-12341300-a9a6-11eb-92f9-a272e91a9736.png)

**Comment by LukasMFR** [comment]
I was able to disable it, or to use "pixel perferct bump" instead of the smoothed one and it looks quite good actually.
Before closing the issue, I would like to know if those settings are correct to use with your pack :

![2021-04-30_11 38 21](https://user-images.githubusercontent.com/41242166/116677504-96879580-a9a8-11eb-8e31-3906ef12833c.png)

EDIT : does disabling parallax occlusion mapping messes up in any way with the effect (cobble stone for instance) ?

**Comment by Poudingue** [comment]
Parallax Occlusion Mapping should be set to On if you want to see the 3D effect I guess
