### ISSUE TITLE
Oddly curved redstone and sea lantern blocks with PTGI HRR

### ISSUE THREAD

**Issue by NovaNap06** [Poudingue/Vanilla-Normals-Renewed#42]
I know it isn't made for a specific shader, but I figured you probably want to know about this. Whatever HRR does differently makes redstone blocks cave in on the sides and sea lanterns curve out it a way that doesn't look intentional. There may be other blocks but those are the two I noticed.

**Comment by NovaNap06** [comment]
I see now that it's something with x16 resolution because there was the same issue with another texture pack on the x16 version.

**Comment by queenbiscuit311** [comment]
turn off POM if you dont want the curve stuff

**Comment by Poudingue** [comment]
That’s intentional, @NovaNap06.
If you don’t like the effect, you can either disable Parallax Occlusion Mapping entirely (this will also remove any other 3D effects such as on cobblestone), turn its intensity down, or remove the corresponding normal texture (sea_lantern_n.png)
