### ISSUE TITLE
Reflections look weird, almost 'inverted' on some blocks only

### ISSUE THREAD

**Issue by JackIt999** [Poudingue/Vanilla-Normals-Renewed#43]
![2022-01-03_12 23 19](https://user-images.githubusercontent.com/54078318/147976565-624b0424-b0dc-4818-9d56-fdf0249b517e.png)

Two blocks on the left look very strange and are not reflecting properly. Two on the right seem to look perfectly normal.
Using SEUS PTGI HRR Test 2.1, Minecraft 1.18.1, Optifine HD U H4

**Comment by Polarite** [comment]
enable full ray tracing option

**Comment by Poudingue** [comment]
Yes, until Cody disables roughness cutoff for metals, you need to enable full ray tracing for it to not look weird.
