### ISSUE TITLE
No parallax mapping on some materials / blocks

### ISSUE THREAD

**Issue by NuclearMeltdown** [Poudingue/Vanilla-Normals-Renewed#44]
I've noticed that some blocks like grass / dirt, stone, gravel, clay, tree trunks, redstone parts like pistons and more don't have any parallax maps on them and look completely flat. Textures don't cast shadows on themselves and there is no depth to them. Is this intended or is this something that's still being worked on in the process of porting the pack to labpbr? These materials look kind of out of place, given that they shouldn't be completely flat like concrete or other smooth, reflective blocks.

**Comment by Poudingue** [comment]
This is mainly because some shaders don’t behave correctly with parallax occlusion mapping, and thus some blocks look bad if I add it. However for certain textures, this looks better even with those shaders so I included it !
