### ISSUE TITLE
Nothing happens when using texture.

### ISSUE THREAD

**Issue by Septillion24** [Poudingue/Vanilla-Normals-Renewed#45]
Unless I'm doing something wrong, nothing happens whenever I use the texture. I've tried 1.18.2 and 1.19 and neither work. 
I'm using the raytracing SEUS PTGI HRR 3 on Iris. Does this just not work with fabric?

Thank you!

**Comment by queenbiscuit311** [comment]
Iris doesn't support PBR. Iris is only using the base textures which are identical to vanilla, and not the material or directional maps. You'd have to use optifine either through forge or optifabric to use the pack unfortunately.

**Comment by Septillion24** [comment]
Ah, that makes sense then. I didn't know that there was an optifine mod for fabric, I'll try that out. After a google search, it looks like they're working on PBR for iris too.
Thank you!

**Comment by queenbiscuit311** [comment]
No problem. Iris does have blanned PBR support but unfortunately the ETA is anyone's guess. There's not an official version of optifine for fabric but someone has a mod that allows the forge version to work on fabric anyways, only issue is that some mods will refuse to work with it.

**Comment by jasondyoungberg** [comment]
Iris now supports PBR as of [version 1.3.0](https://github.com/IrisShaders/Iris/blob/trunk/docs/changelogs/1.3.0/full.md)

Update iris and this issue should be resolved.

**Comment by Septillion24** [comment]
Epic!
