### ISSUE TITLE
Could you recommend graphics and shaders configuration settings?

### ISSUE THREAD

**Issue by Panderine** [Poudingue/Vanilla-Normals-Renewed#5]
Hi, I'm tesing this resource pack with the SEUS PTGI E12 shaders, Could you recommend wich settings to use in order to get those reflections you have in the screenshots?

**Comment by CometSparkle** [comment]
Sorry&nbsp;I&nbsp;can't&nbsp;because&nbsp;I&nbsp;don't&nbsp;have&nbsp;computer


---Original---

**Comment by Poudingue** [comment]
I'd just say to toggle "Full Raytrace Reflection", it helps with rough reflections.

**Comment by CometSparkle** [comment]
OK,&nbsp;I&nbsp;understand,&nbsp;there's&nbsp;no&nbsp;need&nbsp;to&nbsp;reply


---Original---

**Comment by CometSparkle** [comment]
by&nbsp;the&nbsp;way,&nbsp;thanks&nbsp;for&nbsp;providing&nbsp;such&nbsp;an&nbsp;amazing&nbsp;resourcepack.&nbsp;


---Original---
