### ISSUE TITLE
Texture Pack won't show up

### ISSUE THREAD

**Issue by ghost** [Poudingue/Vanilla-Normals-Renewed#6]
Hi, can someone help me figure out why the texture pack isn't showing up on minecraft when I go to change my resource pack? I have the file unzipped and in the correct folder, yet it doesn't show up. I'm on 1.15.2 with optifine installed, along with the SEUS PTGI shaders running.

**Comment by briansemrau** [comment]
Resource packs should be in a zip file in your resource packs folder. Make sure that inside the zip, the pack.mcmeta and other files are at the top level. That is, you shouldn't see another folder called "Vanilla-Normals-Renewed" inside the zip.

**Comment by ghost** [comment]
This worked, thank you!
