### ISSUE TITLE
textur pack does not show

### ISSUE THREAD

**Issue by bobbyturtle** [Poudingue/Vanilla-Normals-Renewed#7]
when i put the pack into the resource folder it does not show up in minecraft. i looked at the files and they were all correct. can anyone help me?

**Comment by jonab03** [comment]
What you may have done is cloned master witch creates a extra folder in the zip witch makes minecraft unable to read it. You will need to repack it so that the pack.mcmeta file is the top layer of the zip or just extract it.

**Comment by Poudingue** [comment]
Yes, you need either to unzip it (extract here, not extract into folder), or you can download a "release" version :
https://github.com/Poudingue/Vanilla-Normals-Renewed/releases
